spring:
  application:    name: PAYMENT-SERVICE
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/paymentservice
    password: Vithal@7757
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    show-sql: 'true'

server:
  port: '8002'
  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  
 
      
      