server:
  port: '8001'

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/orderservice
    password: Vithal@7757
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    show-sql: 'true'  application:    name: ORDER-SERVICE
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
   